name: SeeInv
version: "${pom.version}"
api: ["1.0.8"]
author: PetteriM1
main: me.petterim1.seeinv.Main
description: A Nukkit plugin that allows staff to see and modify players inventories
website: https://nukkitx.com/resources/seeinv.289/
depend: ["FakeInventories"]

commands:
  seeinv:
    description: See player's inventory
    usage: "/seeinv <player> [echest]"
    permission: seeinv.command.use
  editinv:
    description: Edit player's inventory
    usage: "/seeinv <player> [echest]"
    permission: editinv.command.use

permissions:
  seeinv.command.use:
    description: "Allows user to use /seeinv command"
    default: op
  editinv.command.use:
    description: "Allows user to use /editinv command"
    default: op
